name: Build Tauri App (v1)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tauri-build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Generate Tauri icons
        run: npx tauri icon ./icon.png
        working-directory: .

      - name: Build Tauri app
        run: npx tauri build
        working-directory: .

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}-bundle
          path: src-tauri/target/release/bundle/
